---
- name: Create NGINX enabled sites directory
  ansible.builtin.file:
    path: /etc/nginx/enabled
    state: directory
    mode: "0644"
    owner: root
    group: root
  notify:
    - Restart NGINX

- name: Remove default site
  ansible.builtin.file:
    path: /etc/nginx/conf.d/default.conf
    state: absent
  notify:
    - Restart NGINX

- name: Configure NGINX for Radarr
  ansible.builtin.copy:
    src: "{{ item.file }}"
    dest: "{{ item.dest }}"
    mode: "0644"
    owner: root
    group: root
  with_items:
    - file: nginx-radarr.conf
      dest: /etc/nginx/enabled/radarr.conf
    - file: nginx.conf
      dest: /etc/nginx/nginx.conf
  notify:
    - Restart NGINX
